workflows:
  react-web-app:
    name: React Web App
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      node: 18
    scripts:
      - name: Install dependencies
        script: npm ci
      - name: Build
        script: npm run build
    artifacts:
      - dist/**
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
